/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.beandev.contracts.app;

import io.beandev.contracts.list.LinkedList;

import static io.beandev.contracts.utilities.StringUtils.join;
import static io.beandev.contracts.utilities.StringUtils.split;
import static io.beandev.contracts.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

import java.lang.reflect.InvocationTargetException;

public class App {
    public static void main(String[] args) {
        if (args.length > 0) {
            var arg = args[0];
            System.out.println("Hello, " + arg + "!");
            try {
                Class<?> clazz = Class.forName(arg); // To create an instance
                Object obj = clazz.getDeclaredConstructor().newInstance();
                System.out.println(obj);
            } catch (ClassNotFoundException | NoSuchMethodException | InstantiationException | IllegalAccessException |
                     InvocationTargetException e) {
                e.printStackTrace();
            }
        } else {
            System.out.println("Hello, world!");
        }

        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
